### PR TITLE
fix(HostData): use custom version type to handle numbers and strings.

### PR DESCRIPTION
**Pull request by ns3777k**
@AdrianLungu @Luminger

Would you have time to test this before I merge?
Any comments?  😄

### CODE REVIEW

**Comment by AdrianLungu** [comment]
Thanks, will test this right away! 

Would also modifying the host_test with the following change be helpful to have go check if marshalling is done properly ?

```
response, err := client.GetHostsForQuery(options)
if err != nil {
	t.Error(err)
}

_, err = json.Marshal(response)
```

**Comment by AdrianLungu** [comment]
Seems to be working fine on my end!

**Comment by ns3777k** [comment]
Yup, I'll add a test on HostVersion today before merging. I think a couple of tests on unmarshalling will be enough 'cause it's a string so no errors expecting on marshalling.

**Comment by ns3777k** [comment]
Pushed 2.0.1 tag.

**Pull request merged**
