### PR TITLE
Added go get and changed import

### PR DESCRIPTION
**Pull request by pczajkowski**
I can build it only if used like that. Otherwise I get errors.

### CODE REVIEW

**Comment by ns3777k** [comment]
@pczajkowski you don't use go modules, do you?

**Comment by pczajkowski** [comment]
Nope, I'm rather oldschool.

**Comment by ns3777k** [comment]
Cool :-) i'll make a note in readme for old school :-)

**Comment by ns3777k** [comment]
https://github.com/ns3777k/go-shodan/blob/master/README.md

**Comment by pczajkowski** [comment]
Cheers!

**Pull request closed without merging**
